Aufgabe 1: 

Ausgaben sind ->     

System.out.println("Follow the white rabbit...");
System.out.println("Knock knock, Neo.");

Exception wird abgefangen und in Catch abgearbeitet, folglich wird finanly immer ausgeführt.

Aufgabe 2
try { 


} catch (Exception e) {
Es ist gut, dass eine Exception immer exception abfagengen kann.
Aber schlecht, weil man nicht mehr wissen kann, um welches Exception es hier handelt 

}

Aufgabe 3 

Das throw wird verwendet, um eine Ausnahme explizit im Code, 
innerhalb der Funktion oder des Code-Blocks zu deklarieren.

Das throws wird in der Methodensignatur verwendet,
um eine Ausnahme zu deklarieren, die von der Funktion während der Ausführung des Codes ausgelöst werden könnte.